### ISSUE TITLE
Remove authorize.ts and use an alternative method

### ISSUE THREAD

**Issue by EL-MTN** [StuCo-Tech-Committee/stuco-surveys#9]
Authorized.ts contains the emails of all the admins. Best of all, it's open source. We should change that immediately.

**Comment by Cowation** [comment]
Changes made in major-refactor should fix this

**Comment by Cowation** [comment]
https://github.com/StuCo-Tech-Committee/stuco-surveys/commit/5746cb78285d826a4dc3a91191f465c1ab60e209#diff-fd085a2f1c9f7f2d19025398a7d090b2dde2e52bc1431e7f5394606ed03e35db
